### ISSUE TITLE
Frontend Design & Mockups

### ISSUE THREAD

**Issue by cmarkwell** [umbchackers/Judging-App#10]
What design system do we want to use? Manual? Material? Bootstrap? We should probably discuss what we want the frontend to look like at the same time.

**Comment by cmarkwell** [comment]
See milestones for some functionality

**Comment by Flux0s** [comment]
Judges:
- List of tables to visit
  - Description / name of project
- Score submission view
  - This might be a separate page
  - Potentially linked to from the list above

**Comment by Flux0s** [comment]
> What design system do we want to use? Manual? Material? Bootstrap? We should probably discuss what we want the frontend to look like at the same time.

Decided to use [React Bootstrap](https://react-bootstrap.github.io/)
