### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by Flux0s** [umbchackers/Judging-App#14]
- Display the list of tables for the logged in judge
  - retrieved from the backend at '/api/assignments'
- Add functionality to choose top three projects
  - 3 dots on each project

**Comment by hackUMBC-Admin** [comment]
### Connor: 
* Front-end service interface

### Saajid:
* Page that maps project info from the service into project components
  * Must be able to interface with the project components to determine the top 3 choices and send to the service interface
* Project components that have 3 radio buttons for first second and third

**Comment by cmarkwell** [comment]
Done! :)
